# Generated by Django 4.0.6 on 2022-07-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email_address',
            field=models.EmailField(default='anonymouse@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='company_address',
            field=models.TextField(),
        ),
    ]
