# Generated by Django 4.0.6 on 2022-07-28 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('website_name', models.CharField(max_length=150, null=True)),
                ('application_name', models.CharField(max_length=150, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=150)),
                ('company_address', models.TextField()),
                ('country_based', models.CharField(max_length=150)),
                ('email_address', models.EmailField(default='anonymouse@gmail.com', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
