# Generated by Django 4.0.6 on 2022-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='website_url',
            field=models.CharField(default='samsung', max_length=250),
            preserve_default=False,
        ),
    ]
